# run tmux package manager
set -g @plugin 'tmux-plugins/tpm'

# plugins
set -g @catppuccin_flavour 'latte'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'catppuccin/tmux'

# remap prefix from ctrl b to ctrl a
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Pi / modern terminal support
set -g extended-keys on
set -g extended-keys-format csi-u

# scrolling
set -g mouse on
set -g history-limit 100000

# Force mouse wheel to scroll tmux history, even in full-screen TUIs like Pi
bind -n WheelUpPane if -F "#{pane_in_mode}" "send-keys -X -N 3 scroll-up" "copy-mode -e; send-keys -X -N 3 scroll-up"
bind -n WheelDownPane if -F "#{pane_in_mode}" "send-keys -X -N 3 scroll-down" "send-keys -M"

# switch panes using alt arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# colors
set -as terminal-features ",xterm*:RGB"
set -as terminal-features ",screen*:RGB"
set -as terminal-features ",tmux*:RGB"

# vi keybindings
set-option -g mode-keys vi

# open new panes and windows with same path
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# clear history, prefix + K
bind K clear-history

# initialize plugins
run '~/.tmux/plugins/tpm/tpm'
